# Generated by Django 5.0.7 on 2024-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'managed': True},
        ),
        migrations.RemoveIndex(
            model_name='logs',
            name='logs_employe_417fc9_idx',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='logdate',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='logtime',
        ),
        migrations.AddField(
            model_name='logs',
            name='log_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='employeeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
