# Generated by Django 5.0.7 on 2024-08-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='employeeid',
            field=models.CharField(blank=True, null=True),
        ),
    ]
