# Generated by Django 5.0.7 on 2024-09-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_logs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={},
        ),
    ]
