# Generated by Django 5.0.7 on 2024-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_logs_employeeid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logs',
            name='logs_employe_417fc9_idx',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='logdate',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='logtime',
        ),
        migrations.AddField(
            model_name='logs',
            name='log_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
