# Generated by Django 5.0.7 on 2024-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_remove_logs_logs_employe_417fc9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
