# Generated by Django 5.0.7 on 2024-09-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_remove_logs_logs_employe_417fc9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, null=True)),
                ('log_datetime', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('serialno', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'logs_2',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
