# Generated by Django 5.0.7 on 2024-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_logs_options'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='employee',
        #     name='ap_no',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='ar_no',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='cn_no',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
    ]
