# Generated by Django 5.0.7 on 2024-10-28 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_lastlogidmandays'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManDaysMissedPunchAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_status', models.CharField(blank=True, max_length=50, null=True)),
                ('logdate', models.DateField()),
                ('duty_in_1', models.TimeField(blank=True, null=True)),
                ('duty_out_1', models.TimeField(blank=True, null=True)),
                ('duty_in_2', models.TimeField(blank=True, null=True)),
                ('duty_out_2', models.TimeField(blank=True, null=True)),
                ('duty_in_3', models.TimeField(blank=True, null=True)),
                ('duty_out_3', models.TimeField(blank=True, null=True)),
                ('duty_in_4', models.TimeField(blank=True, null=True)),
                ('duty_out_4', models.TimeField(blank=True, null=True)),
                ('duty_in_5', models.TimeField(blank=True, null=True)),
                ('duty_out_5', models.TimeField(blank=True, null=True)),
                ('duty_in_6', models.TimeField(blank=True, null=True)),
                ('duty_out_6', models.TimeField(blank=True, null=True)),
                ('duty_in_7', models.TimeField(blank=True, null=True)),
                ('duty_out_7', models.TimeField(blank=True, null=True)),
                ('duty_in_8', models.TimeField(blank=True, null=True)),
                ('duty_out_8', models.TimeField(blank=True, null=True)),
                ('duty_in_9', models.TimeField(blank=True, null=True)),
                ('duty_out_9', models.TimeField(blank=True, null=True)),
                ('duty_in_10', models.TimeField(blank=True, null=True)),
                ('duty_out_10', models.TimeField(blank=True, null=True)),
                ('employeeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.employee')),
            ],
            options={
                'db_table': 'mandays_missed_punch_attendance',
            },
        ),
    ]
