# Generated by Django 5.0.7 on 2024-12-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country_code',
            field=models.CharField(blank=True, default='IN', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country_name',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
    ]
