volumes:
  postgres_data: {}
  postgres_data_backups: {}
  
  production_redis_data: {}

services:
  django: &django
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    restart: always
    env_file: .env
    environment:
      - ENVIRONMENT=production
      - ALLOWED_HOSTS=*
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always    
    volumes:
      - production_redis_data:/data

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
      - "443:443"  # Map HTTPS port
    volumes:
      - ./frontend:/app
    depends_on:
      - django
    restart: always


  # celery:
  #   container_name: celery
  #   build:
  #     context: ./backend
  #   volumes:
  #     - ./backend:/usr/src/app
  #   depends_on:
  #     - postgres
  #     - redis

  # celery:
  #   <<: *django
  #   command: celery -A backend worker --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #     - django

  # celery-beat:
  #   <<: *django
  #   command: celery -A backend beat --loglevel=info  # Introduce a 5-second delay
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   volumes:
  #     - ./backend/celerybeat-schedule:/app/celerybeat-schedule
  #   depends_on:
  #     - redis
  #     - django
  #   # Remove port mapping for celery-beat:
  #   # ports:
  #   #   - "8082:8000"