volumes:
  postgres_data: {}
  postgres_data_backups: {}
  
  production_redis_data: {}

services:
  django: &django
    build:
      context: ./backend
    image: backend
    depends_on:
      - postgres
      - redis
    ports:
      - "30000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password123@172.30.112.1:5432/skf
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: skf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:6
    
    volumes:
      - production_redis_data:/data

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - django

  celery:
    <<: *django
    command: celery -A backend worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - django

  celery-beat:
    <<: *django
    command: celery -A backend beat --loglevel=info  # Introduce a 5-second delay
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend/celerybeat-schedule:/app/celerybeat-schedule
    depends_on:
      - redis
      - django
    # Remove port mapping for celery-beat:
    # ports:
    #   - "8082:8000"