volumes:
  postgres_data: {}
  postgres_data_backups: {}
  
  production_redis_data: {}

services:
  django: &django
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    restart: always
    environment:
      - ENVIRONMENT=local
      - DEBUG=True
      - SECRET_KEY='}Z(=*+t(]!&&-"!-.pO{*/q8/IFkx)'
      - ALLOWED_HOSTS=10.177.8.143
      - DATABASE_HOST=10.177.8.143
      - DATABASE_PORT=5432
      - DATABASE_NAME=skf
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password123

      # Celery Configuration
      - CELERY_BROKER=redis://10.177.8.143:6379/0
      - CELERY_BACKEND=redis://10.177.8.143:6379/0
      - CELERY_ACCEPT_CONTENT=json
      - CELERY_TASK_SERIALIZER=json
      - CELERY_RESULT_SERIALIZER=json
      - CELERY_TIMEZONE=Asia/Kolkata

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: skf
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password123
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # redis:
  #   image: docker.io/redis:6
    
  #   volumes:
  #     - production_redis_data:/data

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - django
    restart: always

  # celery:
  #   container_name: celery
  #   build:
  #     context: ./backend
  #   volumes:
  #     - ./backend:/usr/src/app
  #   depends_on:
  #     - postgres
  #     - redis

  # celery:
  #   <<: *django
  #   command: celery -A backend worker --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #     - django

  # celery-beat:
  #   <<: *django
  #   command: celery -A backend beat --loglevel=info  # Introduce a 5-second delay
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   volumes:
  #     - ./backend/celerybeat-schedule:/app/celerybeat-schedule
  #   depends_on:
  #     - redis
  #     - django
  #   # Remove port mapping for celery-beat:
  #   # ports:
  #   #   - "8082:8000"