volumes:
  postgres_data: {}
  postgres_data_backups: {}
  
  production_redis_data: {}

services:
  django: &django
    build:
      context: ./backend
    image: backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8001:8000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: skf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:6
    
    volumes:
      - production_redis_data:/data

  celeryworker:
    build:
      context: ./backend
    image: celeryworker
    command: celery -A backend worker --loglevel=info
    depends_on:
      - postgres
      - redis

  celerybeat:
    build:
      context: ./backend
    image: celerybeat
    command: celery -A backend beat --loglevel=info
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - django